account_page = '//li[@id="account"]'
dashboard_menu = '//ul[@id="social-sidebar-menu"]/li[1]'
# Hotel menu
hotels_menu = '//ul[@id="social-sidebar-menu"]//a[@href="#Hotels"]'
hotels_hotels_submenu = '//ul[@id="Hotels"]/li[1]'
hotels_rooms_submenu = '//ul[@id="Hotels"]//a[contains(@href, "rooms")]'
hotels_extras_submenu = '//ul[@id="Hotels"]//a[contains(@href, "extras")]'
hotels_reviews_submenu = '//ul[@id="Hotels"]//a[contains(@href, "reviews")]'
hotels_settings_submenu = '//ul[@id="Hotels"]//a[contains(@href, "settings")]'
logout_button = '//li[@id="logout"]'